seed: 49

dump_cfg_path: "experiments/20240404T053853"
default_dtype: "float32"

data_cfg:
  dataset: "mnist"
  img_size: 32
  split: "test"
  data_path: "img_align_celeba.zip"
    filter_classes:
      - 0
      - 5
      - 9

diffusion_cfg:
  max_time_steps: 1000
  sampling_process: "ddim"
  inference_steps: 32
  pred_type: "v"
  variance_schedule: "cosine"
  to_enforce_zero_terminal_snr: false

train_cfg:
  teacher_cfg:
    teacher_checkpoint:
      directory: "experiments/20240319T105244/checkpoints"
      max_to_keep: 2
    n_channels: 64
  batch_size: 32
  epochs: 5
  checkpoint:
    directory: "experiments/20240404T053853/checkpoints"
    max_to_keep: 2
  model:
    n_channels: 32
    channel_mults:
      - 1
      - 2
      - 4
      - 8
    is_attn:
      - false
      - false
      - true
      - true
    out_channels: 1
    n_blocks: 2
  sample_every: 500
  train_logs_dir: "experiments/20240404T053853/logs"
  patience: -1
  precision: 0.000075
  weight_strategy: "snr"

infer_cfg:
  gen_dir: "experiments/20240404T053853/generated_data/${timestamp}"
  only_last: True
  store_individually: False
  store_gif: False
  store_collage: True
  n_images_approx: 8
