seed: 49

dump_cfg_path: "experiments/${timestamp}"
default_dtype: "float32"

data_cfg:
  dataset: "mnist"
  img_size: 32
  split: "test"
  data_path: "img_align_celeba.zip"

diffusion_cfg:
  max_time_steps: 1000
  sampling_process: "ddim"
  inference_steps: 32
  pred_type: "v"
  variance_schedule: "cosine"
  to_enforce_zero_terminal_snr: false

train_cfg:
  teacher_cfg:
    teacher_checkpoint:
      directory: "experiments/20240319T105244/checkpoints"
      max_to_keep: 2
    n_channels: 64
  batch_size: 32
  epochs: 5
  checkpoint:
    directory: "experiments/${timestamp}/checkpoints"
    max_to_keep: 2
  model:
    n_channels: 32
    channel_mults:
      - 1
      - 2
      - 4
      - 8
    is_attn:
      - false
      - false
      - true
      - true
    out_channels: 1
    n_blocks: 2
  sample_every: 500
  train_logs_dir: "experiments/${timestamp}/logs"
  patience: 5
  precision: 0.000075
  weight_strategy: "snr"

infer_cfg:
  gif_dir: "experiments/${timestamp}/generated_data/${timestamp}/gifs"
  png_dir: "experiments/${timestamp}/generated_data/${timestamp}/pngs"
  ind_dir: "experiments/${timestamp}/generated_data/${timestamp}/eval"
  only_last: True
  store_individually: False
  n_images_approx: 8
