seed: 49

dump_cfg_path: "experiments/20240401T234207"
default_dtype: "float32"

data_cfg:
  dataset: "cifar10"
  img_size: 32
  split: "train"

diffusion_cfg:
  max_time_steps: 500
  sampling_process: "ddim"
  inference_steps: 32
  pred_type: "v"
  variance_schedule: "cosine"
  to_enforce_zero_terminal_snr: false

train_cfg:
  teacher_checkpoint:
    directory: "experiments/20240319T105244/checkpoints"
    max_to_keep: 2
  batch_size: 256
  epochs: 1000
  checkpoint:
    directory: "experiments/20240401T234207/checkpoints"
    max_to_keep: 2
  model:
    n_channels: 64
    channel_mults:
      - 1
      - 2
      - 4
      - 8
    is_attn:
      - false
      - false
      - true
      - true
    out_channels: 3
    n_blocks: 2
  sample_every: 1500
  train_logs_dir: "experiments/20240330T124336/logs"
  patience: 10

infer_cfg:
  gif_dir: "experiments/20240401T234207/generated_data/${timestamp}/gifs"
  png_dir: "experiments/20240401T234207/generated_data/${timestamp}/pngs"
  ind_dir: "experiments/20240401T234207/generated_data/${timestamp}/eval"
  only_last: True
  store_individually: True
  n_images_approx: 10000
